trigger:
  branches:
    include:
      - main
      - master
      - develop
      - release

pr:
  branches:
    include:
      - main
      - master
      - develop
      - release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install sfdx-cli --global
  displayName: 'Install Salesforce CLI'

- script: |
    if [ "$(Build.SourceBranchName)" == "develop" ]; then
      echo "$(SFDX_DEV_AUTH_URL)" > authFile.txt
      sfdx force:auth:sfdxurl:store -f authFile.txt -a targetOrg
      sfdx force:source:deploy -p force-app -u targetOrg
    elif [ "$(Build.SourceBranchName)" == "release" ]; then
      echo "$(SFDX_REL_AUTH_URL)" > authFile.txt
      sfdx force:auth:sfdxurl:store -f authFile.txt -a targetOrg
      sfdx force:source:deploy -p force-app -u targetOrg
    elif [ "$(Build.SourceBranchName)" == "master" ]; then
      echo "$(SFDX_MASTER_AUTH_URL)" > authFile.txt
      sfdx force:auth:sfdxurl:store -f authFile.txt -a targetOrg
      sfdx force:source:deploy -p force-app -u targetOrg
    elif [ "$(Build.SourceBranchName)" == "main" ]; then
      echo "$(SFDX_MAIN_AUTH_URL)" > authFile.txt
      sfdx force:auth:sfdxurl:store -f authFile.txt -a targetOrg
      sfdx force:source:deploy -p force-app -u targetOrg
    fi
  displayName: 'Deploy Based on Branch'
